name: Docker deploy image

on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types: 
      - completed
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_LOWERCASE: knox-aau/access-api

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.IMAGE_NAME_LOWERCASE }}
      - name: Build and push Docker image
        run: |
          docker build --build-arg INTERNAL_KEY=${{ vars.INTERNAL_KEY }} -t ghcr.io/${{ env.IMAGE_NAME_LOWERCASE }} .
          docker push ghcr.io/${{ env.IMAGE_NAME_LOWERCASE }}
