name: Docker deploy image

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/$PROJECT_ID/$IMAGE:$TAG .
          docker save gcr.io/$PROJECT_ID/$IMAGE:$TAG > image.tar
        
      - name: Run Tests 
        run: docker run --network="host" -e POSTGRES_TESTING_DB=${{ env.TEST_POSTGRES_DB }} -e POSTGRES_USER=${{ env.TEST_POSTGRES_USER }} -e POSTGRES_PASSWORD=${{ env.TEST_POSTGRES_PASSWORD }} -e POSTGRES_TESTING_HOST=localhost -e POSTGRES_PORT=5432 gcr.io/$PROJECT_ID/$IMAGE:$TAG go test ./... -v
