name: Test

on:
  push:
  workflow_dispatch:

env:
  TAG: ${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate services.json file
        run: |
          validation_string=$(echo "${response}" | python -c '
            import json,sys
            try:
                with open("services.json") as f:
                    json.load(f)
                print("Valid JSON")
            except Exception as e:
                print("Invalid JSON")
                print(e)
                sys.exit(1)
          ')  
          echo $validation_string   # This should print "Valid JSON" OR "Invalid JSON" with error stacktrace

      - name: Build Docker Image
        run: |
          docker build -t $TAG .
        
      - name: Run Tests 
        run: docker run -e INTERNAL_KEY=test $TAG go test ./... -v
