name: Test

on:
  push:
  workflow_dispatch:

env:
  TAG: ${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate services.json file
        run: |
          response=$(cat services.json)  # Ensure the response contains the valid JSON string
          validation_string=$(echo "${response}" | python -c '
          import json,sys
          obj=None
          try:
              obj=json.load(sys.stdin)
              print("Valid JSON")
          except Exception as e:
              print("Invalid JSON")
              print(e)
              sys.exit(1)
          ')  
          echo $validation_string   # This should print "Valid JSON" OR "Invalid JSON" with error stacktrace
          echo "JOB_LOG=$response" >> $GITHUB_ENV  # This will store the actual JSON into GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t $TAG .
        
      - name: Run Tests 
        run: docker run -e INTERNAL_KEY=test $TAG go test ./... -v
