name: Test

on:
  push:
  workflow_dispatch:

env:
  TAG: ${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t $TAG .
        
      - name: Run Tests 
        run: docker run -e INTERNAL_KEY=test $TAG go test ./... -v
